# Generated by Django 5.0 on 2024-01-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('servicios', '0003_alter_subservicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'TypeProject',
                'verbose_name_plural': 'TypeProjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.pais'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('presupuesto', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.client')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.departamento')),
                ('equipo', models.ManyToManyField(related_name='proyectos_equipo', to='equipos.equipo')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_lider', to='equipos.equipo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.pais')),
                ('servicios', models.ManyToManyField(to='servicios.servicio')),
                ('subservicios', models.ManyToManyField(to='servicios.subservicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.typeproject')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'ProyectoImagen',
                'verbose_name_plural': 'ProyectoImagenes',
                'ordering': ['proyecto'],
            },
        ),
    ]
