# Generated by Django 5.0 on 2024-01-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='pais',
        ),
    ]
