# Generated by Django 6.0.6 on 2026-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
