# Generated by Django 5.0 on 2024-01-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicio',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
