# Generated by Django 6.0.6 on 2026-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_add_comision_topografia_subservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subservicio',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='subservicio',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
