http2 on;

server {
    listen 80;
    server_name magnaingenieriaytopografia.com www.magnaingenieriaytopografia.com;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name localhost;
    return 301 https://localhost$request_uri;
}

server {
    listen 443 ssl;
    server_name magnaingenieriaytopografia.com www.magnaingenieriaytopografia.com m.magnaingenieriaytopografia.com localhost;
    ssl_certificate /etc/letsencrypt/live/magnaingenieriaytopografia.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/magnaingenieriaytopografia.com/privkey.pem;

    client_max_body_size 100M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;

    location /static/ {
        alias /static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
