# Generated by Django 5.0 on 2024-01-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('posicion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos')),
            ],
        ),
    ]
